# Generated by Django 5.1.5 on 2025-10-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_type1_pokemon_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='shiny_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
