# Generated by Django 5.1.5 on 2025-10-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
    ]
